#+TITLE: Research Resources Repository
#+AUTHOR: Guanqun Yang
#+DATE: 12/28/2018

* Introduction
  As a person who loves to keep everything organized, I sometimes find it insufficient
  to keep relevant resources in bookmark bar since I, with high probability, will end up
  forgetting they are there and wasting time discover them repeatedly. Therefore, I decide
  to set up this repository to stash the gems I find during daily learning and research.

  The organization of this repository follows five topics I listed in prologue plus two 
  additional non-technical topics
  1. General articles on research, career and life I find beneficial. Note even for non-English
     articles, I will generally use their (probably inaccurate) English translation since Emacs does not
     support efficient non-English (especially Chinese) input.
  2. Research tools/softwares not listed in [[https://github.com/emptymalei/awesome-research][Awesome Research Tools]] created by Lei Ma, whose
     notes on his/her statistical physics courses motivated me to create this whole set of notes.
  
* Linear Algebra
  
+ [[http://web.stanford.edu/~jduchi/projects/general_notes.pdf][Derivations for Linear Algebra and Optimization]] by John Duchi
* Convex Optimization

+ [[http://web.stanford.edu/~jduchi/projects/general_notes.pdf][Derivations for Linear Algebra and Optimization]] by John Duchi
* Machine Learning

* Deep Learning 


* My Current Research

* General Articles
** Uncategorized
+ [[http://www.adoctorateandbeyond.com/][A Doctorate and Beyond: Building a Career in Engineering and the Physical Sciences]]

  Some concensus and conventions of writing proofs in mathematical community.
** Writing and Presenting
*** Techniques
+ [[http://pgbovine.net/email-tips.htm][Email Writing Tips]] by Philip Guo
+ [[https://sites.math.washington.edu/~lee/Writing/writing-proofs.pdf][Some Remarks on Writing Mathematical Proofs]] by John M. Lee
+ /Air & Light & Time & Space - How Successful Academics Write/ by Helen Sword
  - Interviews of one hundred scholars around world with different backgrounds who thrive
    in the publish-or-perish environment.
*** Tools
+ [[https://thepresentationdesigner.co.uk/5-classic-presentation-fonts/][5 Classic Presentation Fonts]]
  - Five fonts (~Helvetica~, ~Garamond~ and others)  and their history well-suited for presentation. To use
    the fonts mentioned, go to [[https://tex.stackexchange.com/questions/121061/working-with-arial-or-helvetica-fonts][here (for Helvetica)]] or [[https://tex.stackexchange.com/questions/406816/how-can-i-get-a-garamond-font][here (for Garamond)]].




** PhD Application
+ [[http://pgbovine.net/PhD-application-tips.htm][A Five-Minute Guide to Ph.D. Program Applications]] by Philip Guo
  + Some templates of SOPs could be found [[http://pgbovine.net/PhD-application-essay-examples.htm][here]].
** PhD Life
+ [[https://zhuanlan.zhihu.com/p/50597445][My eight years of doing PhD - Academics]] by [[http://www.cs.cmu.edu/~yunwang/][Dr. Yun Wang]] (in Chinese)
+ [[https://zhuanlan.zhihu.com/p/50667670][My eight years of doing PhD - Fun]] by  [[http://www.cs.cmu.edu/~yunwang/][Dr. Yun Wang]] (in Chinese)
+ [[https://mp.weixin.qq.com/s?__biz=MzI1OTA4Mjk3NA==&mid=2650830984&idx=1&sn=f963f564dfe1e01996e3c4545fd5c793][How to be a happy and productive writer]] by [[https://sociology.ubc.ca/profile/yue-qian/][Dr. Qian Yue]] (in Chinese)
  - Note: This is a verbatim of a workshop mainly discussing reading-writing cycle
    for PhD research in sociology. Even though the voices come from a different
    discipline than engineering, the methology, to my opinion, is largely the same and
    feels relatable to my personal experiences.
  - Her [[https://www.weibo.com/p/1001603935693545055068][weibo post]] on the same topic, but in more details (in Chinese).
+ [[https://mp.weixin.qq.com/s/50iNupppOyGLDt4cJmYk3Q][How to manage your time, emotion, research progress as re-tenure faculty members?]] by [[https://sociology.ubc.ca/profile/yue-qian/][Dr. Qian Yue]] (in Chinese)
  - Note: This is an article talking about the author's first year as an assistant professor in sociology.
    Although I am currently still a student, the time/emotion  management part is pretty useful. At the same time, 
    since we are both abroad, the feelings about life in a different country somehow synchronize.

** Career


* Research Tools
** Commenting LaTex Articles
   + [[http://ftp.math.purdue.edu/mirrors/ctan.org/support/latexdiff/doc/latexdiff-man.pdf][latexdiff]]

    It is a Perl script that compares the differences of two ~.tex~ source files
    and marks the significant differences between them, which could be used for
    commenting manuscripts.
   + Using Git

    See [[https://www.zhihu.com/question/22316670/answer/131793794][this post]] (in Chinese), which utilizes git to do version control on manuscripts. But this seems to be useful
    for individual person who is working on notes rather than collaboration on papers.
   + Direct conversion to MSWord readable format
     + latex2rtf: convert to ~.rtf~ file.
     + [[https://pandoc.org/MANUAL.html][pandoc]]: convert to ~.odt~ file.
     + More solutions could be found [[https://tex.stackexchange.com/questions/111886/how-to-convert-a-scientific-manuscript-from-latex-to-word-using-pandoc][here]].
   + Using Overleaf
     
* Coding

