#+TITLE: Research Resources Repository
#+AUTHOR: Guanqun Yang
#+DATE: 12/27/2018

* Introduction
  As a person who loves to keep everything organized, I sometimes find it insufficient
  to keep relevant resources in bookmark bar since I, with high probability, will end up
  forgetting they are there and wasting time discover them repeatedly. Therefore, I decide
  to set up this repository to stash the gems I find during daily learning and research.

  The organization of this repository follows five topics I listed in prologue plus two 
  additional non-technical topics
  1. General articles on research, career and life I find beneficial. Note even for non-English
     articles, I will generally use their (probably inaccurate) English translation since Emacs does not
     support efficient non-English (especially Chinese) input.
  2. Research tools/softwares not listed in [[https://github.com/emptymalei/awesome-research][Awesome Research Tools]] created by Lei Ma, whose
     notes on his/her statistical physics courses motivated me to create this whole set of notes.
  
* Linear Algebra
  

* Convex Optimization


* Machine Learning

* Deep Learning 


* My Current Research

* General Articles
   + [[https://zhuanlan.zhihu.com/p/50597445][My eight years of doing PhD - Academics]] by [[http://www.cs.cmu.edu/~yunwang/][Dr. Yun Wang]] (in Chinese)
   + [[https://zhuanlan.zhihu.com/p/50667670][My eight years of doing PhD - Fun]] by  [[http://www.cs.cmu.edu/~yunwang/][Dr. Yun Wang]] (in Chinese)
   + [[http://www.adoctorateandbeyond.com/][A Doctorate and Beyond: Building a Career in Engineering and the Physical Sciences]] 
* Research Tools
** Commenting LaTex articles
   + [[http://ftp.math.purdue.edu/mirrors/ctan.org/support/latexdiff/doc/latexdiff-man.pdf][latexdiff]]

    It is a Perl script that compares the differences of two ~.tex~ source files
    and marks the significant differences between them, which could be used for
    commenting manuscripts.
   + Using Git

    See [[https://www.zhihu.com/question/22316670/answer/131793794][this post]] (in Chinese), which utilizes git to do version control on manuscripts. But this seems to be useful
    for individual person who is working on notes rather than collaboration on papers.
   + Direct conversion to MSWord readable format
     + latex2rtf: convert to ~.rtf~ file.
     + [[https://pandoc.org/MANUAL.html][pandoc]]: convert to ~.odt~ file.
     + More solutions could be found [[https://tex.stackexchange.com/questions/111886/how-to-convert-a-scientific-manuscript-from-latex-to-word-using-pandoc][here]].
   + Using Overleaf
 
