* Learning Theory
** Introduction
   Just like $(\epsilon,\delta)$ definition of limit in calculus, learning theory tries
   to answer the fundamental questions like "why machines could learn" and therefore it serves
   as the very foundation of machine learning.

   However, before we formally proceed to the details of theory or algorithms, I think it is 
   important to see the *distinctions* between /learning from statistical side/ and 
   /learning from machine learning side/, which is referred to as two different cultures
   in some literature (see [[https://stats.stackexchange.com/questions/6/the-two-cultures-statistics-vs-machine-learning][StackExchange]]).  
*** The first viewpoint
   The author of /All of Statistics/, Larry Wasserman, believes (see [[https://normaldeviate.wordpress.com/2012/06/12/statistics-versus-machine-learning-5-2/][his blog post]])
   there are  *intrinsically no* differences between two fields since they both involve the process of learning from data
   but there *does exist* some research preferences in each community, specifically
   + Statistic emphasizes formal statistical /inference/ (confindence intervals, hypothesis tests,
     optimal estimators) in low dimensional problems. Some topics of interests include survival analysis
     time series, spatial analysis.
   + Machine learning emphasizes high dimensional /prediction/ problems. Some topics of interests
     include online learning, semi-supervised learning, manifold learning, active learning and boosting.
   
  He also provided a table to show that seemingly different terms actually mean the same thing (note
  this table is the combination of his blog post and a table provided in his book /All of Statistics/).

 #+CAPTION: Terminology used in statistics and machine learning community
  |------------------------------+----------------------|
  | Statistics                   | Machine Learning     |
  |------------------------------+----------------------|
  | estsimation                  | learning             |
  | classification/regression    | supervisied learning |
  | clustering                   | unpervisied learning |
  | classifier                   | hypothesis           |
  | data                         | example/instance     |
  | covariate                    | feature              |
  | response                     | label                |
  | frequentist inference        | N/A                  |
  | Bayesian inference           | Bayesian inference   |
  | directed acyclic graph (DAG) | Bayesian net         |
  | large deviation bounds       | PAC learning         |
  | hypothesis                   | N/A                  |
  | confidence interval          | N/A                  |
  |------------------------------+----------------------|
  /Frequentist inference/ and /Bayesian inference/ are again two schools of thoughts in statistics,
  a dialogue-like post to show their differences could be found [[https://stats.stackexchange.com/a/73180/191779][here]] (really interesting read).
*** The second viewpoint
    /Learning from Data/ (Yaser S. Abu-Mostafa et.al.), a book that takes a different approach than
    many other machine learning books and provides a lot of insights, shows the differences 
    not only between statistics and machine learning, but also /learning in data mining/, specifically
    + Statistics shares the basic premises of learning from data, namely the use of a set of observations
      to uncover an underlying process. ... . Because statistics is a mathematical field, emphasis is 
      given to situations where most of the questions can be answered with rigorous proofs. As a result,
      statistics focuses on somewhat idealized models and analyzes them in great detail. ... .Therefore, 
      we end up with weaker results that are nonetheless boradly applicable.
    + Data mining is a practical field that focuses on finding patterns, correlations, or anomalies in large 
      relational database. ... . Technically, data mining is the same as learning from data, with more emphasis
      on data analysis than on prediction.
*** The third viewpoint
    Summary of some answers on [[https://stats.stackexchange.com/questions/6/the-two-cultures-statistics-vs-machine-learning][StackExchange]]:
    + [[https://stats.stackexchange.com/questions/6/the-two-cultures-statistics-vs-machine-learning][Answer 1]]
      1. Statistics papers are overwhelmingly formal and deductive while machine learning papers might not have
       proofs when proposing new approaches.
      2. Statistics still covers topics like survey design, sampling, which are of little concern for machine learning
      3. Machine learning progresses more quickly than statistics since their papers are generally published on conferences.
    + [[https://stats.stackexchange.com/questions/6/the-two-cultures-statistics-vs-machine-learning][Answer 2]]
      
      Statistics emphasizes /inference/ of data generation process while machine learning emphasizes /prediction/ of new
      data with respect to some variables.
    

   
